### ISSUE TITLE
I get this EXCEPTION when navigating 

### ISSUE THREAD

**Issue by rajeshzmoke** [lejard-h/flutter_google_places#22]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building _ScrollableScope:
flutter: 'package:flutter/src/rendering/editable.dart': Failed assertion: line 590 pos 14:
flutter: '_listenerAttached': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderEditable.hasFocus= (package:flutter/src/rendering/editable.dart:590:14)
flutter: #3      _Editable.updateRenderObject (package:flutter/src/widgets/editable_text.dart:1028:9)
flutter: #4      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4430:12)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)

flutter: #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #208    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #209    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #210    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #211    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #212    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #213    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #214    _invoke (dart:ui/hooks.dart:128:13)
flutter: #215    _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderFlex overflowed by 99348 pixels on the bottom.

**Comment by rajeshzmoke** [comment]
This is my navigation code
```
 String birthPlace = await Navigator.of(context).push(
          MaterialPageRoute(
            builder: (BuildContext context) => WillPopScope(
                  onWillPop: requestPop,
                  child: CustomSearchScaffold(),
                ),
          ),
        );
```

The places screen
```
import 'dart:async';

import 'package:flutter_google_places_autocomplete/flutter_google_places_autocomplete.dart';
import 'package:flutter/material.dart';

const kGoogleApiKey = "myrealapikey";

GoogleMapsPlaces _places = GoogleMapsPlaces(kGoogleApiKey);

final searchScaffoldKey = GlobalKey<ScaffoldState>();

Future<Null> displayPrediction(Prediction p, ScaffoldState scaffold) async {
  if (p != null) {
    PlacesDetailsResponse detail = await _places.getDetailsByPlaceId(p.placeId);
    print('detail $detail');
    var lat = detail.result.geometry.location.lat;
    var lng = detail.result.geometry.location.lng;
    print("${p.description} $lat/$lng ");
    Navigator.of(scaffold.context).pop("${p.description}");

    scaffold
        .showSnackBar(SnackBar(content: Text("${p.description} $lat/$lng ")));
  }
}

class CustomSearchScaffold extends GooglePlacesAutocompleteWidget {
  static const String routeName = 'places';
  CustomSearchScaffold()
      : super(apiKey: kGoogleApiKey, language: "en", components: [
          Component(Component.country, "in"),
          Component(Component.country, "us"),
        ]);

  @override
  _CustomSearchScaffoldState createState() => _CustomSearchScaffoldState();
}

class _CustomSearchScaffoldState extends GooglePlacesAutocompleteState {
  @override
  Widget build(BuildContext context) {
    final appBar = AppBar(
      titleSpacing: 20.0,
      automaticallyImplyLeading: false,
      title: AppBarPlacesAutoCompleteTextField(),
      backgroundColor: Color.fromRGBO(57, 73, 171, 1.0),
    );
    final body = GooglePlacesAutocompleteResult(onTap: (p) {
      // displayPrediction(p, searchScaffoldKey.currentState);
    });
    return Scaffold(key: searchScaffoldKey, appBar: appBar, body: body);
  }

  @override
  void onResponseError(PlacesAutocompleteResponse response) {
    super.onResponseError(response);
    searchScaffoldKey.currentState
        .showSnackBar(SnackBar(content: Text(response.errorMessage)));
  }

  @override
  void onResponse(PlacesAutocompleteResponse response) {
    super.onResponse(response);
    if (response != null && response.predictions.isNotEmpty) {
      searchScaffoldKey.currentState
          .showSnackBar(SnackBar(content: Text("Got answer")));
    }
  }
}

```
